PATCH http://localhost:3000/api/v1/account/4
Content-Type: application/json

{
  "firstname": "ppo",
  "lastname": "tata",
  "email": "totot@gmail.com",
  "role": "user",
  "password": "Totott#123"
}
