### Get /account # 1 → success
GET http://localhost:4000/api/v1/account/home/1

### Get /account # 2 → success
GET http://localhost:4000/api/v1/account/home/2

### Get /account # 69 → error 404
GET http://localhost:4000/api/v1/account/home/69

### Get /account # toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/account/home/toto

### Get /account # null → error 401 Unauthorized
GET http://localhost:4000/api/v1/account/home/

### Get /account # toto → error401 Unauthorized
GET http://localhost:4000/api/v1/account/home/toto

### Get /account → success
GET http://localhost:4000/api/v1/account

### Get /account by id 1 → success
GET http://localhost:4000/api/v1/account/1

### Get /account by id 3 → success
GET http://localhost:4000/api/v1/account/3

### Get /account by id 69 → error404 Not Found
GET http://localhost:4000/api/v1/account/69

### Get /account by id toto → error401 Unauthorized
GET http://localhost:4000/api/v1/account/toto

### Get /account # 1 → success
GET http://localhost:4000/api/v1/account/home/1

### Patch /account # 1 → success
PATCH http://localhost:4000/api/v1/account/1
Content-Type: application/json

{
  "firstname": "ppo",
  "lastname": "tata",
  "email": "totot@gmail.com",
  "role":"user",
  "password": "Totott#123"
}

### Patch /account # 1 → error 400 Bad Request
PATCH http://localhost:4000/api/v1/account/
Content-Type: application/json

{
  "firstname": "ppo",
  "lastname": "tata",
  "email": "totot@gmail.com",
  "role":"user",
  "password": "Totott#123"
}

### Patch /account # 1 → error 400 Bad Request
PATCH http://localhost:4000/api/v1/account/1
Content-Type: application/json

{
  "name": "John Doe"
}

### Delete /account # 1 → success
DELETE http://localhost:4000/api/v1/account/1

### Delete /account # 2 → success
DELETE http://localhost:4000/api/v1/account/2

### Delete /account # 69 → error 404 Not Found
DELETE http://localhost:4000/api/v1/account/69

### Delete /account # null → error 400 Bad Request
DELETE http://localhost:4000/api/v1/account/

### Delete /account # toto → error 401 Unauthorized
DELETE http://localhost:4000/api/v1/account/toto

### Post /signup → success
POST http://localhost:4000/api/v1/signup
Content-Type: application/json

{
  "firstname": "ebfgfgvaba",
  "lastname": "tabfFveabreata",
  "email": "tovaevabtot@gmail.com",
  "password": "TotFFott*123",
  "confirmPassword": "TotFFott*123"
}

### Post /signup → error 400 Bad Request
POST http://localhost:4000/api/v1/signup

### Post /login → success
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
  "email": "tovaevabtot@gmail.com",
  "password": "TotFFott*123"
}

### Post /login → error 401 Unauthorized
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
  "email": "totot@gmail.com"
}

### Post /login → error 401 Unauthorized
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
  "password": "Totott#123"
}

### Post /login → error 400 Bad Request
POST http://localhost:4000/api/v1/login

### POST /logout → success
POST http://localhost:4000/api/v1/logout

### GET /home/account/#1 → success
GET http://localhost:4000/api/v1/home/account/1

### GET /home/account/#2 → success
GET http://localhost:4000/api/v1/home/account/2

### GET /home/account/#69 → Error 401 Unauthorized
GET http://localhost:4000/api/v1/home/account/69

### GET /home/account/#toto → Error 401 Unauthorized
GET http://localhost:4000/api/v1/home/account/toto

### GET /home/account/#toto → Error 401 Unauthorized
GET http://localhost:4000/api/v1/home/account/

### GET /home/{id} #1 → success
GET http://localhost:4000/api/v1/home/1

### GET /home/{id} #2 → success
GET http://localhost:4000/api/v1/home/2

### GET /home/{id} #69 → error 404 Not Found
GET http://localhost:4000/api/v1/home/69

### GET /home/{id} #toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/home/toto

### GET /home → success
GET http://localhost:4000/api/v1/home

### POST /home → success
POST http://localhost:4000/api/v1/home
Content-Type: application/json

{
  "name": "My family"
}

### POST /home → error 400 Bad Request
POST http://localhost:4000/api/v1/home

### POST /home → error 400 Bad Request
POST http://localhost:4000/api/v1/home
Content-Type: application/json

{
  "shopping_list": "Mouchoirs"
}

### PATCH /home/{id} #1 → success
PATCH http://localhost:4000/api/v1/home/1
Content-Type: application/json

{
  "name": "Rename my home"
}

### PATCH /home/{id} #toto → error 401 Unauthorized
PATCH http://localhost:4000/api/v1/home/toto
Content-Type: application/json

{
  "name": "Rename my home"
}

### PATCH /home/{id} #1 → 400 Bad Request
PATCH http://localhost:4000/api/v1/home/1

### PATCH /home/{id} # null → 404 Not Found
PATCH http://localhost:4000/api/v1/home/

### DELETE /home/{id} #1 → success
DELETE http://localhost:4000/api/v1/home/1

### DELETE /home/{id} #1 → success
DELETE http://localhost:4000/api/v1/home/toto

### DELETE /home/{id} #1 → error 404 Not Found
DELETE http://localhost:4000/api/v1/home/

### GET /address/home/{id} #1 → success
GET http://localhost:4000/api/v1/address/home/1

### GET /address/home/{id} #2 → success
GET http://localhost:4000/api/v1/address/home/2

### GET /address/home/{id} #69 → error 404 Not Found
GET http://localhost:4000/api/v1/address/home/69

### GET /address/home/{id} #toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/address/home/toto

### GET /address/{id} #1 → success
GET http://localhost:4000/api/v1/address/1

### GET /address/{id} #2 → success
GET http://localhost:4000/api/v1/address/2

### GET /address/{id} #69 → error 404 Not Found
GET http://localhost:4000/api/v1/address/69

### GET /address/{id} #toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/address/toto

### GET /address → success
GET http://localhost:4000/api/v1/address

### POST /address → success
POST http://localhost:4000/api/v1/address
Content-Type: application/json

{
  "street": "rue de la paix",
  "city": "Paris",
  "postal_code": "75000",
  "country": "France"
}

### POST /address → error 400 Bad Request
POST http://localhost:4000/api/v1/address
Content-Type: application/json

{
  "postal_code": "75000",
  "country": "France"
}

### POST /address → error 400 Bad Request
POST http://localhost:4000/api/v1/address
Content-Type: application/json

{
  "city": "Paris",
  "country": "France"
}

### POST /address → error 400 Bad Request
POST http://localhost:4000/api/v1/address
Content-Type: application/json

{
  "city": "Paris",
  "postal_code": "75000"
}

### POST /address → error 400 Bad Request
POST http://localhost:4000/api/v1/address

### PATCH /address/{id} #1 → success
PATCH http://localhost:4000/api/v1/address/1
Content-Type: application/json

{
  "street": "rue de la paix",
  "city": "Paris",
  "postal_code": "75000",
  "country": "France"
}

### PATCH /address/{id} #2 → success
PATCH http://localhost:4000/api/v1/address/2
Content-Type: application/json

{
  "street": "rue de la paix",
  "city": "Paris",
  "postal_code": "75000",
  "country": "France"
}

### PATCH /address/{id} #69 → error 404 Not Found
PATCH http://localhost:4000/api/v1/address/69
Content-Type: application/json

{
  "street": "rue de la paix",
  "city": "Paris",
  "postal_code": "75000",
  "country": "France"
}

### PATCH /address/{id} #toto → error 401 Unauthorized
PATCH http://localhost:4000/api/v1/address/toto
Content-Type: application/json

{
  "street": "rue de la paix",
  "city": "Paris",
  "postal_code": "75000",
  "country": "France"
}

### DELETE /address/{id} #1 → success
DELETE http://localhost:4000/api/v1/address/1

### DELETE /address/{id} #2 → success
DELETE http://localhost:4000/api/v1/address/2

### DELETE /address/{id} #69 → error 404 Not Found
DELETE http://localhost:4000/api/v1/address/69

### DELETE /address/{id} #toto → error 401 Unauthorized
DELETE http://localhost:4000/api/v1/address/toto

### GET /task/account/{id} #1 → success
GET http://localhost:4000/api/v1/task/profile/1

### GET /task/account/{id} #1 → success
GET http://localhost:4000/api/v1/task/profile/2

### GET /task/account/{id} #1 → error 401 Unauthorized
GET http://localhost:4000/api/v1/task/profile/toto

### GET /task/account/{id} #1 → error 404 Not Found
GET http://localhost:4000/api/v1/task/profile/69

### GET /task/{id} #1 → success
GET http://localhost:4000/api/v1/task/1

### GET /task/{id} #2 → success
GET http://localhost:4000/api/v1/task/2

### GET /task/{id} #69 → error 404 Not Found
GET http://localhost:4000/api/v1/task/69

### GET /task/{id} #toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/task/toto

### GET /task/{id}/subtask #1 → success
GET http://localhost:4000/api/v1/task/1/subtask

### GET /task/{id}/subtask #2 → success
GET http://localhost:4000/api/v1/task/2/subtask

### GET /task/{id}/subtask #69 → error 404 Not Found
GET http://localhost:4000/api/v1/task/69/subtask

### GET /task/{id}/subtask #toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/task/toto/subtask

### GET /task → success
GET http://localhost:4000/api/v1/task

### POST /task → success
POST http://localhost:4000/api/v1/task
Content-Type: application/json

{
  "name": "Acheter du pain",
  "start_date": "2024-05-27T10:12Z",
  "end_date": "2024-05-27T10:13Z",
  "status": "à faire"
}

### POST /task → error 404 Not Found
POST http://localhost:4000/api/v1/task
Content-Type: application/json

{
  "name": "Acheter du pain",
  "start_date": "2024-05-27T10:12Z",
  "end_date": "2024-05-27T10:13Z"
}

### POST /task → error 404 Not Found
POST http://localhost:4000/api/v1/task
Content-Type: application/json

{
  "name": "Acheter du pain",
  "start_date": "2024-05-27T10:12Z"
}

### POST /task → error 404 Not Found
POST http://localhost:4000/api/v1/task
Content-Type: application/json

{
  "name": "Acheter du pain"
}

### POST /task → error 404 Not Found
POST http://localhost:4000/api/v1/task


### PATCH /task/{id} #1 → success
PATCH http://localhost:4000/api/v1/task/1
Content-Type: application/json

{
  "name": "Acheter du pain",
  "start_date": "2024-05-27T10:12Z",
  "end_date": "2024-05-27T10:13Z",
  "status": "à faire"
}

### PATCH /task/{id} #1 → success
PATCH http://localhost:4000/api/v1/task/2
Content-Type: application/json

{
  "name": "Acheter du pain",
  "start_date": "2024-05-27T10:12Z",
  "end_date": "2024-05-27T10:13Z",
  "status": "à faire"
}

### PATCH /task/{id} #1 → success
PATCH http://localhost:4000/api/v1/task/69
Content-Type: application/json

{
  "name": "Acheter du pain",
  "start_date": "2024-05-27T10:12Z",
  "end_date": "2024-05-27T10:13Z",
  "status": "à faire"
}

### PATCH /task/{id} #1 → success
PATCH http://localhost:4000/api/v1/task/toto
Content-Type: application/json

{
  "name": "Acheter du pain",
  "start_date": "2024-05-27T10:12Z",
  "end_date": "2024-05-27T10:13Z",
  "status": "à faire"
}

### DELETE /task/{id} #1 → success
DELETE http://localhost:4000/api/v1/task/1

### DELETE /task/{id} #2 → success
DELETE http://localhost:4000/api/v1/task/2

### DELETE /task/{id} #69 → error 404 Not Found
DELETE http://localhost:4000/api/v1/task/69

### DELETE /task/{id} #toto → error 401 Unauthorized
DELETE http://localhost:4000/api/v1/task/toto

# ! A VERIFIER
### GET /account/:id/profile #1 → success
GET http://localhost:4000/api/v1/account/1/profile

### GET /account/:id/profile #2 → success
GET http://localhost:4000/api/v1/account/2/profile

### GET /account/:id/profile #69 → error 404 Not Found
GET http://localhost:4000/api/v1/account/69/profile

### GET /account/:id/profile #toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/account/toto/profile

### GET /home/:id/profile #1 → success
GET http://localhost:4000/api/v1/home/1/profile

### GET /home/:id/profile #2 → success
GET http://localhost:4000/api/v1/home/2/profile

### GET /home/:id/profile #69 → error 404 Not Found
GET http://localhost:4000/api/v1/home/69/profile

### GET /home/:id/profile #toto → error 401 Unauthorized
GET http://localhost:4000/api/v1/home/toto/profile

### GET /profile/:id → success
GET http://localhost:4000/api/v1/profile/1

### GET /profile/:id → success
GET http://localhost:4000/api/v1/profile/2

### GET /profile/:id → error 404 Not Found
GET http://localhost:4000/api/v1/profile/69

### GET /profile/:id → error 401 Unauthorized
GET http://localhost:4000/api/v1/profile/toto

### GET /profile → success
GET http://localhost:4000/api/v1/profile

### POST /profile → success
POST http://localhost:4000/api/v1/profile
Content-Type: application/json

{
  "name": "tata",
  "birthdate": "tabfFveabreata",
  "rôle": "child"
}